# Generated by rust2rpm 27, now modified by hand
# as I've not figured out how to make crate2rpm work.
# Once that happens we can remove this file
#
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           ublk_user_id
Version:        0.1.0
Release:        0.1.0
Summary:        Utility helper for creating block devices in userspace

License:        MIT OR Apache-2.0

URL:            https://github.com/ublk-org/libublk-rs
Source:         ublk_user_id-0.1.0.crate
Source:         ublk_user_id-0.1.0-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  clang-devel

%global _description %{expand:
A utility to extrace user id while creating a block device using ublk.}

%description %{_description}

%prep
%autosetup -n ublk_user_id-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE-APACHE
%license LICENSE-MIT
%license LICENSE.dependencies
%license cargo-vendor.txt
%{_bindir}/ublk_user_id

%changelog
* Wed Nov 19 2025 Tony Asleson <tasleson@redhat.com> 0.1.0-1
- Inital packaging
